# Generated by Django 4.1.6 on 2023-03-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.ManyToManyField(related_name='user_notifications', to='twitter.notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'like'), ('reply', 'reply'), ('retweet', 'retweet'), ('follow', 'follow'), ('follow_request', 'follow_request')], max_length=20),
        ),
    ]
